# manual_test_client.py
import requests
import getpass

# --- CONFIG ---
API_BASE_URL = "http://127.0.0.1:8000"
# This input simulates the clean, standardized text generated by the Gemini AI Engine
CLINICAL_INPUT = "Onset of nausea, fever, and severe right lower abdominal pain 1 day ago; severity: severe."

# --- Authentication Gathering ---
print("\n--- Manual Secure Diagnosis Test ---")
auth_username = input("Enter your username: ").strip()
auth_token = getpass.getpass("Paste your JWT Access Token (Bearer ...): ").strip()

# --- Token Check and Formatting ---
# This ensures the token is correctly passed as "Bearer [token]"
if not auth_token.lower().startswith('bearer '):
    print("WARNING: Automatically adding 'Bearer ' prefix.")
    auth_token = f"Bearer {auth_token}"

# Headers for the secure API call
headers = {
    "Authorization": auth_token, 
    "Content-Type": "application/json"
}

# --- Prediction and Execution ---
try:
    print(f"\n[Sending ML Prediction Request for: {auth_username}]")
    
    response = requests.post(
        f"{API_BASE_URL}/predict_disease",
        headers=headers,
        json={"text": CLINICAL_INPUT},
        timeout=10
    )
    
    # Raise an exception for bad status codes (e.g., 401 Unauthorized)
    response.raise_for_status() 
    
    # Process successful response
    result = response.json()
    
    print("\n--- TEST SUCCESSFUL (200 OK) ---")
    print("Core ML/DB Security Check: PASS ✅")
    print(f"ML Diagnosis: {result['disease']} (Severity: {result['severity']})")
    print(f"Record Saved to User: {result['username']} (ID: {result['user_id']})")
    print("\n---------------------------------")
    print("Your entire Medimate system is confirmed fully functional.")

except requests.exceptions.HTTPError as e:
    print(f"\n--- TEST FAILED: HTTP Error ---")
    print(f"Status Code: {e.response.status_code}")
    print(f"Detail: {e.response.json().get('detail', 'N/A')}")
    if e.response.status_code == 401:
        print("\nACTION: JWT Token is EXPIRED or INVALID. Log in via browser to get a new token.")
    
except requests.exceptions.ConnectionError:
    print("\n--- TEST FAILED: Connection Error ---")
    print("ACTION: Ensure your 'backend_service.py' server is running in Terminal 1.")